name: ci

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    environment: test
    steps:
      -
        name: Login to r.r.c
        uses: docker/login-action@v3
        with:
          registry: registry.rancher.com
          username: ${{ secrets.RSC_USER }}
          password: ${{ secrets.RSC_KEY }}

